#!/usr/bin/env python3
"""Rank Animals questions from target-blind regenerated branch supports."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from helpers import Config, load_config
from model_factory import build_model_adapter
from scripts.animals_belief_recall_ranker import (
    RankerResponseError,
    parse_scores,
    summarize_rankings,
)


SYSTEM_PROMPT = {
    "role": "system",
    "content": (
        "You rank candidate questions for an open-world 20 Questions agent. "
        "The unknown true animal is not provided and may be missing from the "
        "current finite belief support. For each candidate you receive the "
        "actual animal-name supports regenerated by a separate language model "
        "under hypothetical Yes and No answers. Score the expected chance that "
        "the support reached after the answer contains the unknown true animal. "
        "Use the conversation and current support to judge semantic plausibility, "
        "coverage, omissions, and contradictions in each regenerated branch, "
        "including plausible animals newly recovered outside the current support. "
        "Weight Yes and No branch quality by their predictive probabilities. "
        "Do not optimize support size or immediate information gain by itself. "
        "Return only one bare JSON object {\"scores\":[number,...]}, with one "
        "finite score per candidate in original order and larger meaning better."
    ),
}


def prompt_payload(record: dict[str, Any]) -> dict[str, Any]:
    """Build the complete target-free payload from an explicit allowlist."""
    candidates = []
    for index, entry in enumerate(record["candidate_dynamics"]):
        candidates.append(
            {
                "index": index,
                "question": str(entry["question"]),
                "predictive_probability_yes": float(entry["p_yes"]),
                "predictive_probability_no": float(entry["p_no"]),
                "regenerated_support_if_yes": [
                    str(item) for item in entry["support_if_yes"]
                ],
                "regenerated_support_if_no": [
                    str(item) for item in entry["support_if_no"]
                ],
            }
        )
    return {
        "domain": "animals",
        "history": [
            {
                "question": str(item["question"]),
                "answer": str(item["answer"]),
            }
            for item in record["history"]
        ],
        "current_support": [str(item) for item in record["belief_support"]],
        "candidates": candidates,
    }


def build_messages(record: dict[str, Any]) -> list[dict[str, str]]:
    return [
        SYSTEM_PROMPT,
        {
            "role": "user",
            "content": (
                "Score every candidate using only these target-blind branch "
                "supports. The unknown target is not provided.\n"
                + json.dumps(
                    prompt_payload(record),
                    ensure_ascii=True,
                    separators=(",", ":"),
                )
            ),
        },
    ]


def run_ranker(
    records: list[dict[str, Any]],
    runtime_config: Config,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if not runtime_config.model_pairs:
        raise ValueError("ranker config requires one model pair")
    model = build_model_adapter(
        runtime_config.model_pairs[0].questioner,
        config=runtime_config,
    )
    completions = model.chat_complete_messages_batched(
        [build_messages(record) for record in records],
        temperature=runtime_config.generation_temperature_simple,
        block_size=runtime_config.batched_block_size,
        max_new_tokens=runtime_config.openrouter_max_output_tokens,
    )
    if len(completions) != len(records):
        raise RuntimeError("ranker returned the wrong number of completions")
    usage = model.usage_snapshot()
    ranked = []
    for index, (record, completion) in enumerate(zip(records, completions)):
        try:
            scores = parse_scores(completion, len(record["candidate_dynamics"]))
        except ValueError as exc:
            raise RankerResponseError(
                str(exc),
                failing_index=index,
                completions=completions,
                usage=usage,
            ) from exc
        ranked.append(
            {
                **record,
                "belief_recall_scores": scores,
                "raw_ranker_response": completion,
                "model_visible_payload": prompt_payload(record),
            }
        )
    return ranked, usage


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--run-id",
        default="animals-branch-support-ranker-development",
    )
    args = parser.parse_args()

    raw = args.input.read_bytes()
    payload = json.loads(raw)
    records = payload.get("records")
    if not isinstance(records, list):
        raise ValueError("input does not contain a records list")
    config = load_config(str(args.config))
    config.run_id = args.run_id
    args.output_dir.mkdir(parents=True, exist_ok=True)
    try:
        ranked, usage = run_ranker(records, config)
        summary = summarize_rankings(ranked)
    except Exception as exc:
        failure = {
            "schema_version": 1,
            "status": "failed_closed",
            "error": f"{type(exc).__name__}: {exc}",
            "source_sha256": hashlib.sha256(raw).hexdigest(),
            "failing_index": getattr(exc, "failing_index", None),
            "raw_ranker_responses": getattr(exc, "completions", None),
            "usage": getattr(exc, "usage", None),
        }
        (args.output_dir / "BRANCH_RANKING_FAILURE.json").write_text(
            json.dumps(failure, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        raise
    result = {
        "schema_version": 1,
        "status": "development_only",
        "target_blind_prompt_construction": True,
        "run_id": args.run_id,
        "source_path": str(args.input),
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "summary": summary,
        "records": ranked,
        "usage": usage,
    }
    (args.output_dir / "BRANCH_RANKING.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
